Create vmbackup subdir in remote dirs

diff --git a/vmbackuprotate b/vmbackuprotate
--- a/vmbackuprotate
+++ b/vmbackuprotate
@@ -93,7 +93,10 @@ do
 
     echo "Synchronize $remote..."
 
-    rsync -a -H --delete --progress $BAK_DIR/ $remote || { echo >&2 "Synchronization failed for $remote"; continue; }
+    # A 'vmbackup' directory is created in each remote dir
+    # Hardcoding a subdirectory name is not elegant, but it is a simple measure to avoid wreaking havoc
+    # in the system if entering / as remote dir by mistake in the config file.
+    rsync -a -H --delete --progress $BAK_DIR/ $remote/vmbackup || { echo >&2 "Synchronization failed for $remote"; continue; }
 
 done
 
